{"trial_id": "01", "hyperparameters": {"space": [{"class_name": "Choice", "config": {"name": "num_heads", "default": 2, "conditions": [], "values": [2, 4, 8], "ordered": true}}, {"class_name": "Choice", "config": {"name": "d_model", "default": 32, "conditions": [], "values": [32, 64, 128], "ordered": true}}, {"class_name": "Int", "config": {"name": "num_layers", "default": null, "conditions": [], "min_value": 2, "max_value": 6, "step": 1, "sampling": "linear"}}, {"class_name": "Choice", "config": {"name": "d_ff", "default": 128, "conditions": [], "values": [128, 256, 512, 1024], "ordered": true}}, {"class_name": "Boolean", "config": {"name": "dropout", "default": false, "conditions": []}}, {"class_name": "Float", "config": {"name": "peak learning rate", "default": 1e-07, "conditions": [], "min_value": 1e-07, "max_value": 0.01, "step": null, "sampling": "log"}}], "values": {"num_heads": 2, "d_model": 64, "num_layers": 4, "d_ff": 256, "dropout": true, "peak learning rate": 0.00019464966120560521}}, "metrics": {"metrics": {}}, "score": null, "best_step": 0, "status": "FAILED", "message": "Traceback (most recent call last):\n  File \"/home/capybara/Desktop/matura_project_python/tf_env/lib/python3.10/site-packages/keras_tuner/src/engine/base_tuner.py\", line 274, in _try_run_and_update_trial\n    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n  File \"/home/capybara/Desktop/matura_project_python/tf_env/lib/python3.10/site-packages/keras_tuner/src/engine/base_tuner.py\", line 239, in _run_and_update_trial\n    results = self.run_trial(trial, *fit_args, **fit_kwargs)\n  File \"/home/capybara/Desktop/matura_project_python/tf_env/lib/python3.10/site-packages/keras_tuner/src/engine/tuner.py\", line 314, in run_trial\n    obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)\n  File \"/home/capybara/Desktop/matura_project_python/tf_env/lib/python3.10/site-packages/keras_tuner/src/engine/tuner.py\", line 233, in _build_and_fit_model\n    results = self.hypermodel.fit(hp, model, *args, **kwargs)\n  File \"/home/capybara/Desktop/matura_project_python/tf_env/lib/python3.10/site-packages/keras_tuner/src/engine/hypermodel.py\", line 149, in fit\n    return model.fit(*args, **kwargs)\n  File \"/home/capybara/Desktop/matura_project_python/tf_env/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py\", line 122, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"/home/capybara/Desktop/matura_project_python/tf_env/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\n    return fn(*args, **kwargs)\nTypeError: TensorFlowTrainer.fit() got an unexpected keyword argument 'fit_verbose'\n"}